name: Build Dynamic Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build dynamic library
        run: g++ -dynamiclib -o libdynamic.dylib dynamic.cpp

      - name: Verify dynamic library
        run: file libdynamic.dylib
